# Generated by Django 4.2.26 on 2025-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourses', '0002_alter_bourse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bourse',
            name='identifiant_personne',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
