# Generated by Django 4.2.26 on 2026-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourses', '0003_bourse_identifiant_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bourse',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
