# Generated by Django 4.2.26 on 2026-01-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_etudiant_domaine_alter_etudiant_faculte_and_more'),
        ('paiements', '0002_alter_echeancierpaiement_id_alter_paiement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='etudiants.etudiant'),
        ),
    ]
