# Generated by Django 4.2.26 on 2025-12-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='credits_requis',
        ),
    ]
