# Generated by Django 4.x on 2024-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=15)),
                ('code_redoublement', models.CharField(choices=[('N', 'Non redoublant'), ('R', 'Redoublant'), ('T', 'Triplant')], max_length=10)),
                ('boursier', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=10)),
                ('bourse', models.FloatField(default=0)),
                ('numero_inscription', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('faculte', models.CharField(blank=True, max_length=100, null=True)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('cin', models.CharField(blank=True, max_length=12, null=True)),
                ('annee_bacc', models.CharField(blank=True, max_length=4, null=True)),
                ('nationalite', models.CharField(default='Malagasy', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Etudiant/')),
                ('lieu_naissance', models.CharField(blank=True, help_text='Lieu de naissance', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Adresse email personnelle', max_length=100, null=True)),
                ('nom_pere', models.CharField(blank=True, help_text='Nom complet du père', max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, help_text='Nom complet de la mère', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at'],
            },
        ),
    ]
