# Generated by Django 4.2.26 on 2025-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_etudiant_code_redoublement_alter_etudiant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_bacc',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='boursier',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='code_redoublement',
            field=models.CharField(choices=[('N', 'Non redoublant'), ('R', 'Redoublant')], max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='domaine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='faculte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(default='Malagasy', max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
