# Generated by Django 4.2.26 on 2026-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_etudiant_domaine_alter_etudiant_faculte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='bourse_unique_attribuee',
            field=models.BooleanField(default=False, verbose_name='Bourse unique attribuée'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_traitement_doublon',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement du doublon'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='doublon_traite',
            field=models.BooleanField(default=False, verbose_name='Doublon traité'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='est_etudiant_principal',
            field=models.BooleanField(default=False, verbose_name='Étudiant principal (pour bourse)'),
        ),
    ]
