# Generated by Django 4.2.26 on 2025-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_alter_etudiant_annee_bacc_alter_etudiant_boursier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
