# Generated by Django 4.2.26 on 2025-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_alter_etudiant_nom_alter_etudiant_prenom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mention',
            field=models.CharField(blank=True, help_text='Ex: Informatique, Mathématiques, Physique, etc.', max_length=100, null=True),
        ),
    ]
