# Generated by Django 4.2.26 on 2025-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0005_alter_etudiant_options_etudiant_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_redoublement',
            field=models.CharField(choices=[('N', 'Non redoublant'), ('R', 'Redoublant'), ('T', 'Triplant')], max_length=10),
        ),
    ]
