# Generated by Django 4.2.26 on 2025-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_alter_etudiant_code_redoublement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email personnelle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, help_text='Lieu de naissance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_mere',
            field=models.CharField(blank=True, help_text='Nom complet de la mère', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_pere',
            field=models.CharField(blank=True, help_text='Nom complet du père', max_length=100, null=True),
        ),
    ]
