# Generated by Django 4.2.26 on 2025-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_etudiant_email_etudiant_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
