# Generated by Django 4.2.26 on 2025-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_alter_etudiant_numero_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
