# Generated by Django 4.2.26 on 2025-12-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etudiants', '0009_alter_etudiant_numero_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_etudiants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion_locked',
            field=models.BooleanField(default=False),
        ),
    ]
