# Generated by Django 4.2.26 on 2025-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0010_etudiant_locked_at_etudiant_locked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='promotion_locked',
        ),
    ]
